In [1]:
#Indexing with boolean array

import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [3]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [2]:
a[b] #Here a is array and index of array is array itself
#It will print all the values where the value of array b is true we can also replace the value of the array b

a[b] = -1

NameError: name 'a' is not defined

In [3]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b = a > 4
b


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
a[b] = -1 #It will replace the value to -1 where value is true where a > 4