In [1]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [7]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[]