In [2]:
#Iterate over Numpy array -

import numpy as np

a = np.array([[6,7,2],[0,1,2],[9,3,2]])
a

array([[6, 7, 2],
       [0, 1, 2],
       [9, 3, 2]])

In [3]:
for row in a:
    print(row)

[6 7 2]
[0 1 2]
[9 3 2]


In [4]:
for cell in a.flat:
    print(cell)
#flat will flatten the list and print every element

6
7
2
0
1
2
9
3
2


In [4]:
#Iterate over two array simentously

import numpy as np
a = np.arange(12).reshape(3,4)
a
b = np.arange(3,15,4).reshape(3,1)
b
print(a,b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 3]
 [ 7]
 [11]]


In [5]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [ ]:
#This is called Broadcasting in order to do this either shape should be same or one of the array is 1