In [5]:
#Numpy Basic Understanding

#Numpy is extremely used popular python libary. It is heavily used in Scintific computing.
#Numpy's most useful feature is n dimensional array object which is also know as (ndarray)

#Three Main Benefits of Numpy over Python List

#Less Memory( Numpy array takes less bite as it is directly poiniting to values, Python list first points to pointer than the value)
#Fast
#Convivent

#np.array method is used to create a array

#np.arange(Used to set range of the element)
#array.size is the total length of array
#array.itemsize is the size of indiviual element
#array.ndim shows dimesnisons of array
#a.dtype shows data type
#a.shape(3,2) represent the inforamtion on dimensions(3 rows, 2 cols)

#np.zeros((3,4)) creates arrays of zero with 3 rows and 4 cols
#np.ones((3,4))
#np.linspace(1,5,10) it will start at 1 stop at 5 and will create linearly space between 1 to 5

#a.reshape(2,3) reshape the array to 2 rows and 3 cols but it will compitable with intial dimesnsions
#a.ravel() Flaten the array to 1-D array but it will create new array it will not touch the original array

#a.min()
#a.max()
#a.sum()
#np.std(a) --- Standard Deviation
#np.sqrt(a) --- Square of a number
#Axis means dimensions axis(0) -- Means Cols axis(1) --- Means Rows
#a.sum(axis = 0) Sum of Col
#a.sum(axis = 1) Sum of Row
#a.dot(b) --- It will Perform the matrix Product

In [4]:
import numpy as np

a = np.array([1,2,3]) #1-D Array
a[0]


1

In [8]:
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1 + a2
a1 - a2
a1 * a2
a1 / a2

array([0.25, 0.4 , 0.5 ])

In [12]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]]) #2-D Array
a
a.ndim
a.shape


(3, 2)

In [2]:
import numpy as np
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
a = np.array([[1,2],[3,4],[5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [7]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [8]:
a = np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [9]:
a = np.linspace(1,5,20)
a

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
a.sum(axis=0)


60.00000000000001