In [1]:
#Slicing and Stacking -

import numpy as np

a = np.array([6,7,8])
a

array([6, 7, 8])

In [2]:
a[0:2]

array([6, 7])

In [3]:
a[-1]

8

In [6]:
a[0:1]

array([6])

In [8]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [9]:
a[1,2]

3

In [10]:
a[0:2,2]

array([8, 3])

In [13]:
a[:,2]

array([8, 3, 2])

In [14]:
a[-1]

array([9, 3, 2])

In [15]:
a[-1,0:2]

array([9, 3])

In [16]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [24]:
#Stacking
#Stacking means to add two array simentounsly.

import numpy as np

a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a,b)

np.vstack((a,b))

[[0 1]
 [2 3]
 [4 5]] [[ 6  7]
 [ 8  9]
 [10 11]]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [29]:
a = np.arange(30).reshape(2,15)
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
np.hsplit(a,3) #It will horizontally splits array in 3 different array it is also knows as vertical slicing

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [36]:
np.vsplit(a,2) #It will vertically splits array in 3 different array it is also knows as horizontal slicing

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]